- hosts: localhost
  tasks:
  - name: create a instance
    google.cloud.gcp_compute_instance:
      name: "test-instance"
      machine_type: "n1-standard-1"
      disks:
      - auto_delete: 'true'
        boot: 'true'
        initialize_params:
          source_image: "projects/ubuntu-os-cloud/global/images/ubuntu-minimal-2204-jammy-v20221118"
      network_interfaces:
      - network:
          selfLink: "https://www.googleapis.com/compute/v1/projects/cloudside-academy/global/networks/default"
      zone: us-central1-a
      project: cloudside-academy
      auth_kind: serviceaccount
      service_account_file: "./auth.json"
      state: present
